---
title: "Workers Compensation"
author: "Molly Hischke"
date: "3/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Load & Clean Data}
library(readr)
library(tidyr)
library(dplyr)
wc <- read_csv("../data/craftbeer_wc.csv")


policy_years <- wc %>% 
  group_by(Policy_Dim_Key, year) %>% 
  summarize(total_claims = n()) %>% 
  ungroup() %>% 
  group_by(Policy_Dim_Key) %>% 
  summarize(years_with_policy = n()) %>% 
  ungroup()


wc2 <- wc %>% 
  group_by(Policy_Dim_Key, adj_payroll) %>% 
  summarize(total_claims = sum(Claim_Count)) %>% 
  mutate(claim_filed = ifelse(total_claims == 0, 0, 1)) %>% 
  ungroup() %>% 
  full_join(policy_years)
```


```{r Project Proposal Code}
CountModel1 <- glm(total_claims ~ adj_payroll + Policy_Dim_Key + adj_payroll*Policy_Dim_Key, 
                   family = poisson(link = "log"), data = wc2)

summary(CountModel1)

ggplot(data = wc2, aes(x = adj_payroll, y = total_claims)) +
  geom_smooth(method = "glm",
              method.args = list(family = poisson))

CountModel2 <- glm(claim_filed ~ adj_payroll,
                   family = binomial, data = wc2)

summary(CountModel2)
Anova(CountModel2)
ggplot(data = wc2, aes(x = adj_payroll, y = claim_filed)) +
  geom_smooth(method = "glm",
              method.args = list(family = binomial))
```


```{r Size as Categories}
## Separating into different 'groups' for size of brewery
myfun <- function(x) {
  if(x < 10000)
    size = 1
  else if(x >= 10000 && x < 500000)
    size = 2
  else if(x >= 500000)
    size = 3
}

summary(wc$adj_payroll)
wc3 <- wc %>% 
  mutate(size = ifelse(adj_payroll < 100000, 1, 
                       ifelse(adj_payroll < 1000000, 2, 3))) 
wc4 <- wc3 %>% 
  group_by(size, year) %>% 
  summarize(total = n())

library(ggplot2)
ggplot() +
  geom_line(data = wc2, aes(x = year, y = adj_payroll, colour = Policy_Dim_Key))
write.csv(wc2, 'group_by(Policy_Dim_Key).csv')
```


```{r Testing out original data}
# Trying out some other models using the original dataset.
Model1 <- glm(Claim_Count ~ adj_payroll + Policy_Dim_Key + 
                adj_payroll*Policy_Dim_Key, family = binomial, data = wc)
summary(Model1)
Anova(Model1)

# Creating a TempData set to plot Model1
TempData <- data.frame(adj_payroll = seq(from = 0, to = 30000000, by = 20000))
TempData$Mod1Pred <- predict(Model1, newdata = TempData, type = "response")
ggplot(data = TempData, aes(x = adj_payroll, y = Mod1Pred)) +
  geom_line(lwd = 2)

ggplot(data = wc, aes(x = adj_payroll, y = Claim_Count)) +
  geom_smooth(method = "glm",
              method.args = list(family = binomial))
```


```{r More Models}

# Trying out a bunch of different models to see what they look like.
model1 <- lm(Claim_Count ~ adj_payroll, data = wc)
plot(model1, which = 1)

model2 <- glm(Claim_Count ~ adj_payroll, family = poisson(link = "log"), 
              data = wc3)

model3 <- glm(total ~ adj_payroll, family = poisson(link = "log"), 
              data = wc4)

library(car)
summary(model2)
Anova(model2)
plot(residuals(model3, type = "pearson") ~ fitted(model3))
```


